# CETL-MSOR 2022 Beyond alt text: Creating explorable objects in place of images in digital resources. {-}

The digital resources used to support students at university are required to be accessible. This includes any images they may contain. If a picture tells 1,000 words then writing alt text for the 1,000+ images on mathcentre, the post-16 maths resource sharing website, is going to take quite a while. However there is an alternative - convert these images to explorable accessible digital objects. A screen reader can do the heavy lifting for the words, and all students will benefit from an interactive resource. 

A team from the University of Bath and Coventry University have been working together to explore the conversion of images to digital objects. This session will cover what the teams have learned, based on the objectives of the project. 

The session will aim to: 

- Offer guidance on how to use the digital tools Desmos and Geogebra to create digital objects in place of images, and share insight on which is best to convert different types of images. 
- Expose the size of the conversion task for the resources on the mathcentre website. 
- Set out a framework to allow the maths support community to collaborate on the mathcentre image conversion task.  

[View the source code to see how this gitbook was created here](https://github.com/BathMASH/CETL-MSOR-2022-Beyond-alt-text)
